export const CONNECTED_TO_PEER = 'CONNECTED_TO_PEER';
export const DISCONNECTED_FROM_PEER = 'DISCONNECTED_FROM_PEER';
export const CONNECTING_TO_PEER = 'CONNECTING_TO_PEER';
export const DISCONNECTING_FROM_PEER = 'DISCONNECTING_FROM_PEER';
export const RECEIVED_MESSAGE = 'RECEIVED_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SOMEONE_CONNECTED_TO_PEER = 'SOMEONE_CONNECTED_TO_PEER';
