export const CONNECTED_WITH_PEER = 'CONNECTED_TO_PEER';
export const DISCONNECTED_FROM_PEER = 'DISCONNECTED_FROM_PEER';
export const CONNECTING_WITH_PEER = 'CONNECTING_TO_PEER';
export const RECEIVED_MESSAGE = 'RECEIVED_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const CREATED_PEER = 'CREATED_PEER';
export const DELETED_PEER = 'DELETED_PEER';
