export const CONNECTED_WITH_PEER = 'CONNECTED_TO_PEER';
export const DISCONNECTED_FROM_PEER = 'DISCONNECTED_FROM_PEER';
export const CONNECTING_WITH_PEER = 'CONNECTING_TO_PEER';
export const RECEIVED_DATA_FROM_PEER = 'RECEIVED_DATA_FROM_PEER';
export const SEND_DATA_OVER_PEER = 'SEND_DATA_OVER_PEER';
export const CREATED_PEER = 'CREATED_PEER';
export const DELETED_PEER = 'DELETED_PEER';
