/* eslint-disable import/prefer-default-export */
export const GAINED_LICHESS_TOKEN = 'GAINED_LICHESS_TOKEN';
export const LICHESS_TOKEN_REVOKED = 'LICHESS_TOKEN_REVOKED';
export const LICHESS_LOGIN_ERROR = 'LICHESS_LOGIN_ERROR';
export const LICHESS_REFRESHED_TOKEN = 'LICHESS_REFRESHED_TOKEN';
