/* eslint-disable import/prefer-default-export */
export const GAINED_LICHESS_CREDENTIALS = 'GAINED_LICHESS_CREDENTIALS';
export const LICHESS_CREDENTIALS_REVOKED = 'LICHESS_CREDENTIALS_REVOKED';
export const LICHESS_LOGIN_ERROR = 'LICHESS_LOGIN_ERROR';
export const LICHESS_REFRESHED_TOKEN = 'LICHESS_REFRESHED_TOKEN';
export const LICHESS_LOGGING_IN = 'LICHESS_LOGGING_IN';
export const LICHESS_CHALLENGE_RECEIVED = 'LICHESS_CHALLENGE_RECEIVED';
export const LICHESS_EVENT_CHALLENGE = 'LICHESS_EVENT_CHALLENGE';
export const LICHESS_EVENT_GAME_START = 'LICHESS_EVENT_GAME_START';
export const LICHESS_EVENT_GAME_FINISH = 'LICHESS_EVENT_GAME_FINISH';
export const SENT_LICHESS_CHALLENGE = 'SENT_LICHESS_CHALLENGE';