export const CREATE_PLAYER_POOL = 'CREATE_PLAYER_POOL';
export const DELETE_PLAYER_POOL = 'DELETE_PLAYER_POOL';
export const ESTABLISHED_CONNECTION_TO_PLAYER = 'ESTABLISHED_CONNECTION_TO_PLAYER';
export const RECEIVED_SUBSCRIBE_REQUEST = 'RECEIVED_SUBSCRIBE_REQUEST';
export const RECEIVED_UNSUBSCRIBE_REQUEST = 'RECEIVED_UNSUBSCRIBE_REQUEST';
export const RECEIVED_LICHESS_CHALLENGE_COMMAND = 'RECEIVED_LICHESS_CHALLENGE_COMMAND';
export const RECEIVED_MEMBERS_UPDATE = 'RECEIVED_MEMBERS_UPDATE';
export const RECEIVED_LICHESS_ACCEPT_CHALLENGE_COMMAND = 'RECEIVED_LICHESS_ACCEPT_CHALLENGE_COMMAND';